import { toSlug }  from './formatting.js';

export function getContent(data) {
const scriptBlock = '```';

return `---
layout: src/layouts/Default.astro
title: Integrations
navMenu: false
# Set to true when launched
navSitemap: false
navSearch: false
# This file is auto-generated by docs/tools/MarkdownGenerator (home.js)
---

<ul>
${getCategories(data)}
</ul>
`;
}

function getCategories(categories) {
    const output = [];
    for(let name in categories) {
        output.push(`
<li>

<img src="https://i.octopus.com/library/step-templates/${name}.png" alt="${name}" onerror="this.src='https://i.octopus.com/library/step-templates/other.png';" width="55px" height="55px" /> [${name}](${`/integrations/${toSlug(name)}`})

</li>
`);
    }

    return output.join('');
}
