import { toSlug }  from './formatting.js';

export function getContent(name, data) {
const scriptBlock = '```';

return `---
# This file is auto-generated by docs/tools/MarkdownGenerator (index.js)
layout: src/layouts/Default.astro
title: '${name}'
navMenu: false
# Set to true when launched
navSitemap: false
navSearch: false
---

<ul>
${getSteps(name, data)}
</ul>
`;
}

function getSteps(name, data) {
    const sorted = data.templates.sort((a, b) => String(a.name).localeCompare(String(b.name)))
    const output = [];
    for(let step of sorted) {
        output.push(`
<li>

![${name}](https://i.octopus.com/library/step-templates/${name}.png) [${step.name}](${`/integrations/${toSlug(name)}/${toSlug(step.name)}`})

</li>
        `);
    }

    return output.join('');
}
