name: Pull Request build and deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  branch_validation:
    uses: OctopusDeploy/microsite-deployment/.github/workflows/microsite-deployment-branch.yml@main
    with:
      octopus_project_name: "Docs Microsite"
      package_id: "DocsMicrosite"
      node_version: '20'
    secrets: inherit