name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  branch_validation:
    uses: OctopusDeploy/microsite-deployment/.github/workflows/microsite-deployment-full.yml@main
    with:
      octopus_project_name: 'Docs Microsite'
      package_id: 'DocsMicrosite'
      node_version: '22'
    secrets: inherit
